### ISSUE TITLE
PF

### ISSUE THREAD

**Issue by moniyama** [Marinacb7/SAP010-cipher#2]
Parabéns @Marinacb7 ! O projeto está funcional e o código está bem organizado! 

OAs para o proximo projeto:
- HTML semântico (SEO/acessibilidade)

Conversamos tbm sobre:
- Usar uma ferramenta de prototipação
- Usar um kanban para o planejamento
- git: mensagens de commits mais descritivas
- se aprofundar em `for..in` e `for..of`
- números mágicos

**Comment by Marinacb7** [comment]
Fiz a revisão e alterações de acordo com o que foi conversado durante a PF.
